# Generated by Django 2.2.1 on 2019-05-21 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0005_auto_20190520_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='learner',
            name='middle_name',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
