# Generated by Django 2.2.5 on 2020-02-25 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('attendance_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attendance_schooldays', models.IntegerField()),
                ('attendance_absentdays', models.IntegerField()),
                ('attendance_presentdays', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('enrollment_id', models.IntegerField(primary_key=True, serialize=False)),
                ('enrollment_quarter', models.IntegerField()),
                ('enrollment_yearlevel', models.IntegerField()),
                ('enrollment_section', models.CharField(max_length=4)),
                ('enrollment_attendance', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('grade_gradeid', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='RemedialClasses',
            fields=[
                ('remedial_id', models.IntegerField(primary_key=True, serialize=False)),
                ('remedial_learningarea', models.IntegerField()),
                ('remedial_classmark', models.IntegerField()),
                ('remedial_finalgrade', models.IntegerField()),
                ('remedial_remarks', models.CharField(max_length=4)),
                ('remedial_startdate', models.IntegerField()),
                ('remedial_enddate', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schoolyear_schooldays', models.IntegerField()),
                ('schoolyear_schoolyears', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.IntegerField(primary_key=True, serialize=False)),
                ('student_first_name', models.CharField(max_length=255)),
                ('student_middle_name', models.CharField(max_length=255)),
                ('student_last_name', models.CharField(max_length=255)),
                ('student_birthdate', models.DateTimeField()),
                ('student_age', models.IntegerField()),
                ('student_deped_lrd', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentsBehavior',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('behavior_statement', models.CharField(max_length=4)),
                ('behavior_quarter', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_subjectid', models.IntegerField(primary_key=True, serialize=False)),
                ('subject_name', models.CharField(max_length=4)),
            ],
        ),
    ]
