# Generated by Django 2.2.1 on 2019-05-19 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0002_auto_20190520_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='lrn',
            field=models.BigIntegerField(null=True, unique=True),
        ),
    ]
