# Generated by Django 2.2.1 on 2019-05-21 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentdb', '0006_auto_20190521_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learner',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='learner',
            name='middle_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
